import React from 'react';
import { X, Printer, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function BusinessPlanModal({ isOpen, onClose, planContent, loading }) {
    if (!isOpen) return null;

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white dark:bg-slate-900 w-full max-w-4xl rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 flex flex-col max-h-[90vh] overflow-hidden">

                {/* Header - Not printed */}
                <div className="flex items-center justify-between p-4 sm:p-6 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 print:hidden">
                    <div className="flex items-center gap-2">
                        <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                            <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-slate-900 dark:text-white">AI Business Plan</h2>
                            <p className="text-xs text-slate-500 dark:text-slate-400">Generated by UrbanSpend Intelligence</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2 sm:gap-4">
                        <button
                            onClick={handlePrint}
                            disabled={loading || !planContent}
                            className="flex items-center gap-2 px-4 py-2 bg-slate-900 hover:bg-slate-800 dark:bg-white dark:hover:bg-slate-100 text-white dark:text-slate-900 rounded-xl font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            <Printer className="w-4 h-4" />
                            <span className="hidden sm:inline">Print / Save PDF</span>
                        </button>
                        <button
                            onClick={onClose}
                            className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors"
                        >
                            <X className="w-5 h-5" />
                        </button>
                    </div>
                </div>

                {/* Content Area */}
                <div className="flex-1 overflow-y-auto p-6 sm:p-10 bg-white dark:bg-slate-900 print:p-0">
                    {loading ? (
                        <div className="h-full flex flex-col items-center justify-center space-y-4 text-slate-500 min-h-[400px]">
                            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div>
                            <p className="animate-pulse font-medium">Synthesizing local data & financial projections...</p>
                        </div>
                    ) : planContent ? (
                        <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:text-slate-900 dark:prose-headings:text-slate-100 prose-h1:text-3xl prose-h1:font-extrabold prose-h2:text-xl prose-h2:mt-8 prose-h2:border-b prose-h2:border-slate-200 dark:prose-h2:border-slate-800 prose-h2:pb-2 prose-strong:text-blue-700 dark:prose-strong:text-blue-400 marker:text-blue-500 prose-li:my-1 print:prose-slate print:text-black">
                            <ReactMarkdown>{planContent}</ReactMarkdown>
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-slate-400 min-h-[400px]">
                            <FileText className="w-12 h-12 mb-4 opacity-20" />
                            <p>No business plan generated yet.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
